[package]
name = "tui-time"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
libc = "0.2.180"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["rt", "macros", "net", "sync"] }
tui-big-text = "0.8.1"
